//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Makao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int Id { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> Score1 { get; set; }
        public Nullable<int> Cycle { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
